version: "3"
services:
  dbserver:
    container_name: mysql5.6.38
    image: mysql:5.6.38
    environment:
      MYSQL_DATABASE: COVID19
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      # 起動スクリプト
      - ./docker/mysql:/docker-entrypoint-initdb.d
      # MySQLの設定ファイル
      - ./docker/mysql/config:/etc/mysql/conf.d
      # DBの永続化
      - mysql_db:/var/lib/mysql
    restart: always
  app:
    container_name: spring_boot
    build: ./
    depends_on:
      # dbserverが起動してから、appを起動
      - dbserver
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      # mysqlの接続設定 host:portはコンテナ名指定
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://dbserver/COVID19"
      spring.datasource.username: "root"
      spring.datasource.password: "admin"
    restart: always
# DBの永続化先
volumes:
  mysql_db:
    driver: local

networks:
  default:
    external:
      name: shared