#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:mysql://localhost:3306/COVID19?characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=admin

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: covid19hostman@gmail.com
    password: covid0033
    properties: 
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true

---
spring:
  profiles:
    active: localhost

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/COVID19
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  profiles: docker-compose
  datasource:
    url: jdbc:mysql://dbserver/COVID19
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

#---
#spring:
#  profiles:
#    active: localhost
#
#---
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/COVID19?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#---
#spring:
#  profiles: docker-compose
#  datasource:
#    url: jdbc:mysql://dbserver/COVID19?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update