CREATE TABLE IF NOT EXISTS `COUNTRY_MASTER` (
  `country_code` VARCHAR(2) NOT NULL,
  `country_name` VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AF','Afghanistan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AL','Albania');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('DZ','Algeria');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AD','Andorra');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AO','Angola');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AG','Antigua and Barbuda');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AR','Argentina');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AM','Armenia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AU','Australia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AT','Austria');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AZ','Azerbaijan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BS','Bahamas');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BH','Bahrain');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BD','Bangladesh');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BB','Barbados');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BY','Belarus');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BE','Belgium');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BZ','Belize');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BJ','Benin');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BT','Bhutan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BO','Bolivia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BA','Bosnia and Herzegovina');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BW','Botswana');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BR','Brazil');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BN','Brunei Darussalam');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BG','Bulgaria');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BF','Burkina Faso');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('BI','Burundi');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('KH','Cambodia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CM','Cameroon');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CA','Canada');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CV','Cape Verde');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CF','Central African Republic');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TD','Chad');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CL','Chile');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CN','China');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CO','Colombia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('KM','Comoros');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CG','Congo (Brazzaville)');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CD','Congo (Kinshasa)');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CR','Costa Rica');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('HR','Croatia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CU','Cuba');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CY','Cyprus');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CZ','Czech Republic');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CI','Côte d Ivoire');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('DK','Denmark');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('DJ','Djibouti');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('DM','Dominica');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('DO','Dominican Republic');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('EC','Ecuador');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('EG','Egypt');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SV','El Salvador');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GQ','Equatorial Guinea');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ER','Eritrea');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('EE','Estonia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ET','Ethiopia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('FJ','Fiji');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('FI','Finland');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('FR','France');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GA','Gabon');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GM','Gambia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GE','Georgia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('DE','Germany');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GH','Ghana');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GR','Greece');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GD','Grenada');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GT','Guatemala');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GN','Guinea');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GW','Guinea-Bissau');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GY','Guyana');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('HT','Haiti');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('VA','Holy See (Vatican City State)');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('HN','Honduras');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('HU','Hungary');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('IS','Iceland');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('IN','India');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ID','Indonesia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('IR','Iran, Islamic Republic of');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('IQ','Iraq');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('IE','Ireland');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('IL','Israel');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('IT','Italy');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('JM','Jamaica');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('JP','Japan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('JO','Jordan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('KZ','Kazakhstan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('KE','Kenya');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('KR','Korea (South)');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('KW','Kuwait');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('KG','Kyrgyzstan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LA','Lao PDR');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LV','Latvia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LB','Lebanon');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LS','Lesotho');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LR','Liberia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LY','Libya');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LI','Liechtenstein');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LT','Lithuania');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LU','Luxembourg');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MK','Macedonia, Republic of');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MG','Madagascar');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MW','Malawi');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MY','Malaysia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MV','Maldives');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ML','Mali');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MT','Malta');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MR','Mauritania');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MU','Mauritius');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MX','Mexico');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MD','Moldova');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MC','Monaco');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MN','Mongolia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ME','Montenegro');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MA','Morocco');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MZ','Mozambique');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('MM','Myanmar');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('NA','Namibia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('NP','Nepal');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('NL','Netherlands');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('NZ','New Zealand');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('NI','Nicaragua');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('NE','Niger');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('NG','Nigeria');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('NO','Norway');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('OM','Oman');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PK','Pakistan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PS','Palestinian Territory');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PA','Panama');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PG','Papua New Guinea');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PY','Paraguay');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PE','Peru');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PH','Philippines');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PL','Poland');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('PT','Portugal');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('QA','Qatar');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('XK','Republic of Kosovo');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('RO','Romania');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('RU','Russian Federation');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('RW','Rwanda');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('KN','Saint Kitts and Nevis');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LC','Saint Lucia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('VC','Saint Vincent and Grenadines');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SM','San Marino');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ST','Sao Tome and Principe');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SA','Saudi Arabia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SN','Senegal');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('RS','Serbia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SC','Seychelles');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SL','Sierra Leone');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SG','Singapore');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SK','Slovakia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SI','Slovenia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SO','Somalia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ZA','South Africa');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SS','South Sudan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ES','Spain');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('LK','Sri Lanka');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SD','Sudan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SR','Suriname');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SZ','Swaziland');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SE','Sweden');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('CH','Switzerland');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('SY','Syrian Arab Republic (Syria)');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TW','Taiwan, Republic of China');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TJ','Tajikistan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TZ','Tanzania, United Republic of');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TH','Thailand');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TL','Timor-Leste');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TG','Togo');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TT','Trinidad and Tobago');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TN','Tunisia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('TR','Turkey');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('UG','Uganda');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('UA','Ukraine');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('AE','United Arab Emirates');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('GB','United Kingdom');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('US','United States of America');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('UY','Uruguay');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('UZ','Uzbekistan');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('VE','Venezuela (Bolivarian Republic)');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('VN','Viet Nam');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('EH','Western Sahara');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('YE','Yemen');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ZM','Zambia');
INSERT INTO COUNTRY_MASTER (country_code, country_name) VALUES ('ZW','Zimbabwe');
