CREATE TABLE IF NOT EXISTS `MEMBER_INFORMATION` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email_address` VARCHAR(30) NOT NULL,
  `firstname` VARCHAR(10) NOT NULL,
  `lastname` VARCHAR(10) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `isDeleted` VARCHAR(2) DEFAULT '0',  
  `updated_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(`id`),
  UNIQUE(`email_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;